spring:
  data:
    redis:
      host: 172.16.12.15
      port: 7004
      password:
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

# 二维码配置
qrcode:
  # 二维码有效期（秒）
  expire:
    seconds: 300
  width: 100
  height: 100
